---defines.lua---

VB_RESERVE_COUNT = 1024
ID_NUM_MAX = 0xffff

local i = 0
local j = 1
local function Define_VB_Element(name, num)
	local s = ''
	for k = 0, num - 1 do
		s = s..name..'_'..k..' = {LOC = '..i..', FLAG = '..j..'} '
		i = i + 1
		j = j << 1
	end
	load(s)(name, num)
end

Define_VB_Element('VB_ELEM_FLOAT1', 4)
--Define_VB_Element('VB_ELEM_FLOAT2', 4)
Define_VB_Element('VB_ELEM_FLOAT3', 4)
Define_VB_Element('VB_ELEM_FLOAT4', 4)
Define_VB_Element('VB_ELEM_INT1', 4)
Define_VB_Element('VB_ELEM_UINT1', 4)

Define_VB_Element('VB_ELEM_MAX', 1)

SIZE_INDEX = SIZE_UINT1

SIZE_WRITE_ID = SIZE_USHORT1

cGI.FORMAT_WRITE_ID = cGI.FORMAT_R16_UINT

cGI.FORMAT_PICK_ID = cGI.FORMAT_R16_UINT

AddVertexID = CAddUShort1

PickByTexture = CPickByTextureU16
--PickByTexture = CPickByTexture

VB_ELEM_ID = VB_ELEM_UINT1_0

APPEND = -1

Z_2D = 1

g_sizeFunc = {}
g_sizeFunc[CAddFloat1] = 4
--g_sizeFunc[CAddFloat2] = 8
g_sizeFunc[CAddFloat3] = 12
g_sizeFunc[CAddFloat4] = 16
g_sizeFunc[CAddInt1] = 4
g_sizeFunc[CAddUInt1] = 4
g_sizeFunc[CAddUShort1] = 2
g_sizeFunc[CAddUByte4] = 4
g_sizeFunc[CAddMatrix] = CMatrix._size

DC_DEFAULT = 1
DC_SORTED_1 = 2
DC_MTL_MERGED = 3
DC_SORTED_2 = 4

-- SIZE_FLOAT1 = 4
-- SIZE_FLOAT2 = 8
-- SIZE_FLOAT3 = 12
-- SIZE_FLOAT4 = 16
-- SIZE_USHORT1 = 2
-- SIZE_UINT1 = 4

-- cGI.SHADER_STAGE_VERTEX_BIT
-- cGI.SHADER_STAGE_FRAGMENT_BIT

-- cGI.FORMAT_R16_UINT
-- cGI.FORMAT_R32_UINT
-- cGI.FORMAT_R32_SINT
-- cGI.FORMAT_R32_SFLOAT
-- cGI.FORMAT_R32G32_UINT
-- cGI.FORMAT_R32G32_SINT
-- cGI.FORMAT_R32G32_SFLOAT
-- cGI.FORMAT_R32G32B32_UINT
-- cGI.FORMAT_R32G32B32_SINT
-- cGI.FORMAT_R32G32B32_SFLOAT
-- cGI.FORMAT_R32G32B32A32_UINT
-- cGI.FORMAT_R32G32B32A32_SINT
-- cGI.FORMAT_R32G32B32A32_SFLOAT
-- cGI.FORMAT_B8G8R8A8_UNORM

-- cGI.RESOURCE_TYPE_SAMPLER
-- cGI.RESOURCE_TYPE_COMBINED_IMAGE_SAMPLER
-- cGI.RESOURCE_TYPE_SAMPLED_IMAGE
-- cGI.RESOURCE_TYPE_STORAGE_IMAGE
-- cGI.RESOURCE_TYPE_UNIFORM_TEXEL_BUFFER
-- cGI.RESOURCE_TYPE_STORAGE_TEXEL_BUFFER
-- cGI.RESOURCE_TYPE_UNIFORM_BUFFER
-- cGI.RESOURCE_TYPE_STORAGE_BUFFER
-- cGI.RESOURCE_TYPE_UNIFORM_BUFFER_DYNAMIC
-- cGI.RESOURCE_TYPE_STORAGE_BUFFER_DYNAMIC
-- cGI.RESOURCE_TYPE_INPUT_ATTACHMENT

-- cGI.PRIMITIVE_TOPOLOGY_POINT_LIST
-- cGI.PRIMITIVE_TOPOLOGY_LINE_LIST
-- cGI.PRIMITIVE_TOPOLOGY_LINE_STRIP
-- cGI.PRIMITIVE_TOPOLOGY_TRIANGLE_LIST
-- cGI.PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP
-- cGI.PRIMITIVE_TOPOLOGY_TRIANGLE_FAN

-- cGI.POLYGON_MODE_FILL
-- cGI.POLYGON_MODE_LINE
-- cGI.POLYGON_MODE_POINT

-- cGI.CULL_MODE_NONE
-- cGI.CULL_MODE_FRONT_BIT
-- cGI.CULL_MODE_BACK_BIT

-- cGI.COMPARE_OP_NEVER
-- cGI.COMPARE_OP_LESS
-- cGI.COMPARE_OP_EQUAL
-- cGI.COMPARE_OP_LESS_OR_EQUAL
-- cGI.COMPARE_OP_GREATER
-- cGI.COMPARE_OP_NOT_EQUAL
-- cGI.COMPARE_OP_GREATER_OR_EQUAL
-- cGI.COMPARE_OP_ALWAYS

-- cGI.BLEND_FACTOR_ZERO
-- cGI.BLEND_FACTOR_ONE
-- cGI.BLEND_FACTOR_SRC_COLOR
-- cGI.BLEND_FACTOR_ONE_MINUS_SRC_COLOR
-- cGI.BLEND_FACTOR_DST_COLOR
-- cGI.BLEND_FACTOR_ONE_MINUS_DST_COLOR
-- cGI.BLEND_FACTOR_SRC_ALPHA
-- cGI.BLEND_FACTOR_ONE_MINUS_SRC_ALPHA
-- cGI.BLEND_FACTOR_DST_ALPHA
-- cGI.BLEND_FACTOR_ONE_MINUS_DST_ALPHA
-- cGI.BLEND_FACTOR_CONSTANT_COLOR
-- cGI.BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR
-- cGI.BLEND_FACTOR_CONSTANT_ALPHA
-- cGI.BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA
-- cGI.BLEND_FACTOR_SRC_ALPHA_SATURATE
-- cGI.BLEND_FACTOR_SRC1_COLOR
-- cGI.BLEND_FACTOR_ONE_MINUS_SRC1_COLOR
-- cGI.BLEND_FACTOR_SRC1_ALPHA
-- cGI.BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA

-- cGI.BLEND_OP_ADD
-- cGI.BLEND_OP_SUBTRACT
-- cGI.BLEND_OP_REVERSE_SUBTRACT
-- cGI.BLEND_OP_MIN
-- cGI.BLEND_OP_MAX